**Ejercicio 3:**

i. Reproducir la matriz B:

[[0.4 0.41 0.42 0.43 0.44]  \\
[0.45 0.46 0.47 0.48 0.49] \\
[0.5 0.51 0.52 0.53 0.54] \\
[0.55 0.56 0.57 0.58 0.59] \\
[0.6 0.61 0.62 0.63 0.64] \\
[0.65 0.66 0.67 0.68 0.69] \\
[0.7 0.71 0.72 0.73 0.74] \\
[0.75 0.76 0.77 0.78 0.79]]

ii. Unir B con el resultado del ejercicio anterior \\
2.ii para obtener una matriz de 8 lineas y 13 columnas.

iii. Agregar una linea al final con el promedio de cada columna

iv. Agregar una columna al final con el valor maximo de cada fila

v. Guardar en un archivo.

In [51]:
import numpy as np
a = np.array(np.arange(1,65)).reshape([8,8])
A = a.T
A[A % 10 == 3] = -99
A
from numpy.core.fromnumeric import reshape
B = np.arange(0.4, 0.80, 0.01).reshape(8,5)
B
C = np.concatenate((A, B), axis = 1).reshape(8,13)
M = np.mean(C, axis = 0)
M
C1 = np.append(C, [M], axis=0)
C1
m = np.max(C1, axis = 1)
C2 = np.concatenate((C1, m.reshape(9,1)), axis = 1)
C2
np.savetxt('Ejercicio3', C2, delimiter=',')